# Perfil por defecto: dev
spring.profiles.default=dev

# Servidor
server.port=8080

# JPA / Hibernate (compartido entre perfiles)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# JWT
app.jwt.secret=claveSuperSecretaParaJWTToken2024ExamenFinalSpringBootSeguridad
app.jwt.expiration-ms=86400000
