# Base de datos H2 en memoria (perfil dev)
spring.datasource.url=jdbc:h2:mem:examenfinal
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
